# Generated by Django 3.0.5 on 2020-04-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Not Started', max_length=30)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inactive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Denial',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kidsapp.Task')),
                ('visit_id', models.CharField(blank=True, max_length=30, null=True)),
                ('carrier_code', models.CharField(blank=True, max_length=30, null=True)),
                ('carrier', models.CharField(blank=True, max_length=150, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=10, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_of_service', models.DateField(blank=True, null=True)),
            ],
            bases=('kidsapp.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kidsapp.TaskUser'),
        ),
    ]
