# Generated by Django 3.0.5 on 2020-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Archive', 'Archive')], default='Not Started', max_length=30),
        ),
    ]
