# Generated by Django 3.0.5 on 2020-04-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0002_auto_20200429_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='denial',
            name='amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denial',
            name='date_of_denial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denial',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
