# Generated by Django 3.0.5 on 2020-04-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsapp', '0003_auto_20200430_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denial',
            name='amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='denial',
            name='procedure',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
